import React from "react";
import { Permissions } from "../constants";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faPieChart,
    faUser,
    faTruck,
    faUserGroup,
    faHome,
    faBoxes,
    faPrint,
    faBookmark,
    faBoxOpen,
    faMoneyCheckDollar,
    faMoneyBills,
    faQuoteRight,
    faDollarSign,
    faReceipt,
    faArrowRight,
    faArrowLeft,
    faEnvelope,
    faCartShopping,
    faChartColumn,
    faGear,
    faMapLocation,
    faBasketShopping,
    faSms,
    faCube,
    faFile,
    faBook,
    faBookReader,
    faUserFriends,
    faLayerGroup,
    faAtlas,
    faGlobe,
    faTags,
    faHandPaper,
    faSwatchbook,
    faRupee,
    faCogs,
    faCog,
    faFrog,
    faTruckFast,
    faBoxTissue,
    faWindowRestore,
    faSquareCaretRight,
} from "@fortawesome/free-solid-svg-icons";
import { getFormattedMessage } from "../shared/sharedMethod";
import { ShieldLock } from "react-bootstrap-icons";

export default [
    {
        title: "elibrary.title",
        name: "Elibrary",
        fontIcon: <FontAwesomeIcon icon={faBook} />,
        to: "/admin/pos/erp",
        class: "d-flex",
        is_submenu: "true",
        permission: "",
        subPath: {
            lmsDashboardSubPath: "/admin/pos/lms-dashboard",
            booksSubPath: "/admin/pos/books",
            booksCirculationSubPath: "/admin/pos/books-circulation",
            membersSubPath: "/admin/pos/members",
            genresSubPath: "/admin/pos/genres",
            authorsSubPath: "/admin/pos/authors",
            publishersSubPath: "/admin/pos/publishers",
            bookLanguagesSubPath: "/admin/pos/book-languages",
            tagsSubPath: "/admin/pos/tags",
            membershipPlansSubPath: "/admin/pos/membership-plans",
            subscriptionsPlansSubPath: "/admin/pos/subscriptions",
            booksSeriesPlansSubPath: "/admin/pos/books-series",
            bookRequestsPlansSubPath: "/admin/pos/book-requests",
            penaltiesSubPath: "/admin/pos/penalties",
            lmsSettings: "/admin/pos/lms-settings",
        },
        subMenu: [
            {
                title: "LMSdashboard.title",
                name: "LMSdashboard",
                fontIcon: <FontAwesomeIcon icon={faPieChart} />,
                to: "/admin/pos/lms-dashboard",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("LMSdashboard.title"),
                        to: "/admin/pos/lms-dashboard",
                    },
                ],
            },
            {
                title: "books.title",
                name: "All books",
                fontIcon: <FontAwesomeIcon icon={faBook} />,
                to: "/admin/pos/books",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("books.title"),
                        to: "/admin/pos/books",
                    },
                ],
            },
            {
                title: "issued-books.title",
                name: "Issued books",
                fontIcon: <FontAwesomeIcon icon={faSquareCaretRight} />,
                to: "/admin/pos/issued-books",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("issued-books.title"),
                        to: "/admin/pos/books",
                    },
                ],
            },
            {
                title: "reserved-books.title",
                name: "Reserved books",
                fontIcon: <FontAwesomeIcon icon={faWindowRestore} />,
                to: "/admin/pos/reserved-books",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("reserved-books.title"),
                        to: "/admin/pos/books",
                    },
                ],
            },
            {
                title: "books-circulation.title",
                name: "books-circulation",
                fontIcon: <FontAwesomeIcon icon={faBookReader} />,
                to: "/admin/pos/books-circulation",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("books-circulation.title"),
                        to: "/admin/pos/books-circulation",
                    },
                ],
            },
            {
                title: "upcomming-books.title",
                name: "upcomming-books",
                fontIcon: <FontAwesomeIcon icon={faTruckFast} />,
                to: "/admin/pos/upcomming-books",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("upcomming-books.title"),
                        to: "/admin/pos/upcomming-books",
                    },
                ],
            },
            {
                title: "members.title",
                name: "members",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/admin/pos/members",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("members.title"),
                        to: "/admin/pos/members",
                    },
                ],
            },
            {
                title: "genres.title",
                name: "genres",
                fontIcon: <FontAwesomeIcon icon={faLayerGroup} />,
                to: "/admin/pos/genres",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("genres.title"),
                        to: "/admin/pos/genres",
                    },
                ],
            },
            {
                title: "authors.title",
                name: "authors",
                fontIcon: <FontAwesomeIcon icon={faUserFriends} />,
                to: "/admin/pos/authors",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("authors.title"),
                        to: "/admin/pos/authors",
                    },
                ],
            },
            {
                title: "publishers.title",
                name: "publishers",
                fontIcon: <FontAwesomeIcon icon={faAtlas} />,
                to: "/admin/pos/publishers",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("publishers.title"),
                        to: "/admin/pos/publishers",
                    },
                ],
            },
            {
                title: "book-languages.title",
                name: "book-languages",
                fontIcon: <FontAwesomeIcon icon={faGlobe} />,
                to: "/admin/pos/book-languages",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("book-languages.title"),
                        to: "/admin/pos/book-languages",
                    },
                ],
            },
            {
                title: "tags.title",
                name: "tags",
                fontIcon: <FontAwesomeIcon icon={faTags} />,
                to: "/admin/pos/tags",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("tags.title"),
                        to: "/admin/pos/tags",
                    },
                ],
            },
            {
                title: "membership-plans.title",
                name: "membership-plans",
                fontIcon: <FontAwesomeIcon icon={faHandPaper} />,
                to: "/admin/pos/membership-plans",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("membership-plans.title"),
                        to: "/admin/pos/membership-plans",
                    },
                ],
            },
            {
                title: "subscription.title",
                name: "subscription",
                fontIcon: <FontAwesomeIcon icon={faHandPaper} />,
                to: "/admin/pos/subscriptions",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("subscription.title"),
                        to: "/admin/pos/subscriptions",
                    },
                ],
            },
            {
                title: "books-series.title",
                name: "books-series",
                fontIcon: <FontAwesomeIcon icon={faSwatchbook} />,
                to: "/admin/pos/books-series",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("books-series.title"),
                        to: "/admin/pos/books-series",
                    },
                ],
            },
            {
                title: "book-request.title",
                name: "book-request",
                fontIcon: <FontAwesomeIcon icon={faBook} />,
                to: "/admin/pos/book-requests",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("book-request.title"),
                        to: "/admin/pos/book-request",
                    },
                ],
            },
            {
                title: "penalties.title",
                name: "penalties",
                fontIcon: <FontAwesomeIcon icon={faRupee} />,
                to: "/admin/pos/penalties",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("penalties.title"),
                        to: "/admin/pos/penalties",
                    },
                ],
            },
            {
                title: "cms.title",
                name: "CMS",
                fontIcon: <FontAwesomeIcon icon={faLayerGroup} />,
                to: "/admin/pos/lms-settings",
                class: "d-flex",
                is_submenu: "true",
                permission: "",
                subPath: {
                    cmsSubPath: "/admin/pos/lms-settings",
                    cmsHomeSettingSubPath: "/admin/pos/lms-home-settings",
                    cmsTestimonialsSubPath: "/admin/pos/lms-testimonials",
                },
                subMenu: [
                    {
                        title: "settings.title",
                        name: "LMSsettings",
                        fontIcon: <FontAwesomeIcon icon={faGear} />,
                        to: "/admin/pos/lms-settings",
                        class: "d-flex",
                        permission: "",
                    },
                    {
                        title: "home-settings.title",
                        name: "HomeSettings",
                        fontIcon: <FontAwesomeIcon icon={faCogs} />,
                        to: "/admin/pos/lms-home-settings",
                        class: "d-flex",
                        permission: "",
                    },
                    {
                        title: "testimonials.title",
                        name: "Testimonials",
                        fontIcon: <FontAwesomeIcon icon={faQuoteRight} />,
                        to: "/admin/pos/lms-testimonials",
                        class: "d-flex",
                        permission: "",
                    },
                ],
            },
        ],
    },

    {
        title: "erp.title",
        name: "ERP",
        fontIcon: <FontAwesomeIcon icon={faFrog} />,
        to: "/admin/pos/sales",
        class: "d-flex",
        is_submenu: "true",
        permission: "",
        subPath: {
            SubPath: "/admin/pos/pos-dashboard",
            productsSubPath: "/admin/pos/products",
            adjustmentsSubPath: "/admin/pos/adjustments",
            quotationsSubPath: "/admin/pos/quotations",
            purchasesSubPath: "/admin/pos/purchases",
            salesSubPath: "/admin/pos/sales",
            transfersSubPath: "/admin/pos/transfers",
            expensesSubPath: "/admin/pos/expenses",
            expensesSubPath: "/admin/pos/expenses",
            suppliersSubPath: "/admin/pos/suppliers",
            rolesSubPath: "/admin/pos/roles",
            warehouseSubPath: "/admin/pos/warehouse",
            reportSubPath: "/admin/pos/report",
            currenciesSubPath: "/admin/pos/currencies",
            emailTemplatesSubPath: "/admin/pos/email-templates",
            lmposSettingsSubPath: "/admin/pos/lmpos-settings",
        },
        subMenu: [
            {
                title: "POSdashboard.title",
                name: "dashboard",
                fontIcon: <FontAwesomeIcon icon={faPieChart} />,
                to: "/admin/pos/pos-dashboard",
                class: "d-flex",
                permission: "",
                items: [
                    {
                        title: getFormattedMessage("POSdashboard.title"),
                        to: "/admin/pos/pos-dashboard",
                    },
                ],
            },
            {
                title: "products.title",
                name: "products",
                fontIcon: <FontAwesomeIcon icon={faBoxes} />,
                to: "/admin/pos/products",
                class: "d-flex",
                is_submenu: "true",
                permission: Permissions.MANAGE_PRODUCTS,
                subPath: {
                    productsSubPath: "/admin/pos/products",
                    categoriesSubPath: "/admin/pos/product-categories",
                    brandsSubPath: "/admin/pos/brands",
                    unitsSubPath: "/admin/pos/units",
                    barcodeSubPath: "/admin/pos/print/barcode",
                },
                subMenu: [
                    {
                        title: "products.title",
                        to: "/admin/pos/products",
                        name: "products",
                        class: "d-flex",
                        fontIcon: <FontAwesomeIcon icon={faBoxes} />,
                        permission: Permissions.MANAGE_PRODUCTS,
                    },
                    {
                        title: "product.categories.title",
                        name: "product categories",
                        fontIcon: <FontAwesomeIcon icon={faBoxOpen} />,
                        to: "/admin/pos/product-categories",
                        class: "d-flex",
                        permission: Permissions.MANAGE_PRODUCT_CATEGORIES,
                    },
                    {
                        title: "brands.title",
                        name: "brands",
                        fontIcon: <FontAwesomeIcon icon={faBookmark} />,
                        to: "/admin/pos/brands",
                        path: "/admin/pos/create-brand",
                        class: "d-flex",
                        permission: Permissions.MANAGE_BRANDS,
                    },
                    {
                        title: "units.title",
                        name: "units",
                        fontIcon: <FontAwesomeIcon icon={faQuoteRight} />,
                        to: "/admin/pos/units",
                        class: "d-flex",
                        permission: Permissions.MANAGE_UNITS,
                    },
                    {
                        title: "print.barcode.title",
                        name: "print barcode",
                        fontIcon: <FontAwesomeIcon icon={faPrint} />,
                        to: "/admin/pos/print/barcode",
                        class: "d-flex",
                        permission: Permissions.MANAGE_PRODUCTS,
                    },
                ],
            },
            {
                title: "adjustments.title",
                name: "adjustments",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/admin/pos/adjustments",
                class: "d-flex",
                permission: Permissions.MANAGE_ADJUSTMENTS,
                items: [
                    {
                        title: getFormattedMessage("adjustments.title"),
                        to: "/admin/pos/adjustments",
                    },
                ],
            },
            {
                title: "quotations.title",
                name: "quotations.title",
                fontIcon: <FontAwesomeIcon icon={faBasketShopping} />,
                to: "/admin/pos/quotations",
                class: "d-flex",
                permission: Permissions.MANAGE_QUOTATION,
                items: [
                    {
                        title: getFormattedMessage("quotations.title"),
                        to: "/admin/pos/quotations",
                    },
                ],
            },
            {
                title: "purchases.title",
                name: "purchases",
                fontIcon: <FontAwesomeIcon icon={faReceipt} />,
                to: "/admin/pos/purchases",
                class: "d-flex",
                is_submenu: "true",
                permission: Permissions.MANAGE_PURCHASE,
                subPath: {
                    purchasesSubPath: "/admin/pos/purchases",
                    purchaseReturnSubPath: "/admin/pos/purchase-return",
                },
                subMenu: [
                    {
                        title: "purchases.title",
                        name: "purchases",
                        fontIcon: <FontAwesomeIcon icon={faReceipt} />,
                        to: "/admin/pos/purchases",
                        class: "d-flex",
                        permission: Permissions.MANAGE_PURCHASE,
                    },
                    {
                        title: "purchases.return.title",
                        name: "purchases return",
                        fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                        to: "/admin/pos/purchase-return",
                        class: "d-flex",
                        permission: Permissions.MANAGE_PURCHASE_RETURN,
                    },
                ],
            },
            // {
            //     title: "sales.title",
            //     name: "sales",
            //     fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
            //     to: "/admin/pos/sales",
            //     class: "d-flex",
            //     is_submenu: "true",
            //     permission: Permissions.MANAGE_SALE,
            //     subPath: {
            //         salesSubPath: "/admin/pos/sales",
            //         salesReturnSubPath: "/admin/pos/sale-return",
            //     },
            //     subMenu: [
            //         {
            //             title: "sales.title",
            //             name: "sales",
            //             fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
            //             to: "/admin/pos/sales",
            //             class: "d-flex",
            //             permission: Permissions.MANAGE_SALE,
            //         },
            //         {
            //             title: "sales-return.title",
            //             name: "sales return",
            //             fontIcon: <FontAwesomeIcon icon={faArrowRight} />,
            //             to: "/admin/pos/sale-return",
            //             class: "d-flex",
            //             permission: Permissions.MANAGE_SALE_RETURN,
            //         },
            //     ],
            // },
            {
                title: "transfers.title",
                name: "transfers",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/admin/pos/transfers",
                class: "d-flex",
                permission: Permissions.MANAGE_TRANSFERS,
                items: [
                    {
                        title: getFormattedMessage("transfers.title"),
                        to: "/admin/pos/transfers",
                    },
                ],
            },
            {
                title: "expenses.title",
                name: "expenses",
                fontIcon: <FontAwesomeIcon icon={faMoneyBills} />,
                to: "/admin/pos/expenses",
                class: "d-flex",
                is_submenu: "true",
                permission: Permissions.MANAGE_EXPENSES,
                subPath: {
                    expensesSubPath: "/admin/pos/expenses",
                    expenseCategoriesSubPath: "/admin/pos/expense-categories",
                },
                subMenu: [
                    {
                        title: "expenses.title",
                        name: "expenses",
                        fontIcon: <FontAwesomeIcon icon={faMoneyBills} />,
                        to: "/admin/pos/expenses",
                        class: "d-flex",
                        permission: Permissions.MANAGE_EXPENSES,
                    },
                    {
                        title: "expense.categories.title",
                        name: "expense categories",
                        fontIcon: <FontAwesomeIcon icon={faMoneyCheckDollar} />,
                        class: "d-flex",
                        permission: Permissions.MANAGE_EXPENSES_CATEGORIES,
                        to: "/admin/pos/expense-categories",
                    },
                ],
            },
            
            {
                title: "pepole.title",
                name: "Pepoles",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/admin/pos/suppliers",
                class: "d-flex",
                is_submenu: "true",
                subPath: {
                    customerSubPath: "/admin/pos/customers",
                    userSubPath: "/admin/pos/users",
                    suppliareSubPath: "/admin/pos/suppliers",
                },
                permission: Permissions.MANAGE_SUPPLIERS,
                subMenu: [
                    {
                        title: "suppliers.title",
                        name: "suppliers",
                        fontIcon: <FontAwesomeIcon icon={faTruck} />,
                        to: "/admin/pos/suppliers",
                        class: "d-flex",
                        permission: Permissions.MANAGE_SUPPLIERS,
                    },
                    {
                        title: "customers.title",
                        name: "customers",
                        fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
                        to: "/admin/pos/customers",
                        class: "d-flex",
                        permission: Permissions.MANAGE_CUSTOMERS,
                    },
                    {
                        title: "users.title",
                        name: "users",
                        fontIcon: <FontAwesomeIcon icon={faUser} />,
                        to: "/admin/pos/users",
                        class: "d-flex",
                        permission: Permissions.MANAGE_USER,
                    },
                ],
            },
            {
                title: "roles.permissions.title",
                name: "roles",
                fontIcon: <ShieldLock />,
                to: "/admin/pos/roles",
                class: "d-flex",
                permission: Permissions.MANAGE_ROLES,
                items: [
                    {
                        title: getFormattedMessage("roles.title"),
                        to: "/admin/pos/roles",
                    },
                ],
            },
            // {
            //     title: "warehouse.title",
            //     name: "warehouse",
            //     fontIcon: <FontAwesomeIcon icon={faHome} />,
            //     to: "/admin/pos/warehouse",
            //     class: "d-flex",
            //     permission: Permissions.MANAGE_WAREHOUSES,
            //     items: [
            //         {
            //             title: getFormattedMessage("warehouse.title"),
            //             to: "/admin/pos/warehouse",
            //         },
            //     ],
            // },

            {
                title: "reports.title",
                name: "reports",
                fontIcon: <FontAwesomeIcon icon={faChartColumn} />,
                to: "/admin/pos/report/report-warehouse",
                path: "/admin/pos/report/report-sale",
                stockPath: "/admin/pos/report/report-stock",
                purchasePath: "/admin/pos/report/report-purchase",
                topSellingPath: "/admin/pos/report/report-top-selling-products",
                stockDetailPath: "/admin/pos/report/report-detail-stock",
                productQuantityAlertPath:
                    "/admin/pos/report/report-product-quantity",
                supplierReportPath: "/admin/pos/report/suppliers",
                profitLossReportPath: "/admin/pos/report/profit-loss",
                supplierReportDetailsPath:
                    "/admin/pos/report/suppliers/details",
                bestCustomerReportPath: "/admin/pos/report/best-customers",
                customerReportPath: "/admin/pos/report/customers",
                customerReportDetailsPath:
                    "/admin/pos/report/customers/details",
                class: "d-flex",
                isSamePrefix: "true",
                permission: Permissions.MANAGE_REPORTS,
                subTitles: [
                    { title: "warehouse.reports.title" },
                    { title: "sale.reports.title" },
                    { title: "stock.reports.title" },
                    { title: "purchase.reports.title" },
                    { title: "top-selling-product.reports.title" },
                    { title: "product.quantity.alert.reports.title" },
                    { title: "supplier.report.title" },
                    { title: "best-customer.report.title" },
                    { title: "customer.report.title" },
                    { title: "customer.report.title" },
                    { title: "profit-loss.reports.title" },
                    { title: "best-customer.report.title" },
                ],
                items: [
                    {
                        title: getFormattedMessage("warehouse.reports.title"),
                        to: "/admin/pos/report/report-warehouse",
                    },
                    {
                        title: getFormattedMessage("sale.reports.title"),
                        to: "/admin/pos/report/report-sale",
                    },
                    {
                        title: getFormattedMessage("stock.reports.title"),
                        to: "/admin/pos/report/report-stock",
                        detail: "/admin/pos/report/report-detail-stock",
                    },
                    {
                        title: getFormattedMessage("purchase.reports.title"),
                        to: "/admin/pos/report/report-purchase",
                    },
                    {
                        title: getFormattedMessage(
                            "top-selling-product.reports.title"
                        ),
                        to: "/admin/pos/report/report-top-selling-products",
                    },
                    {
                        title: getFormattedMessage(
                            "product.quantity.alert.reports.title"
                        ),
                        to: "/admin/pos/report/report-product-quantity",
                    },
                    // {
                    //     title: "Supplier Report",
                    //     to: '/admin/pos/report/suppliers',
                    // },
                    {
                        title: getFormattedMessage("supplier.report.title"),
                        to: "/admin/pos/report/suppliers",
                        detail: "/admin/pos/report/suppliers/details",
                    },
                    {
                        title: getFormattedMessage("profit-loss.reports.title"),
                        to: "/admin/pos/report/profit-loss",
                    },
                    {
                        title: getFormattedMessage(
                            "best-customer.report.title"
                        ),
                        to: "/admin/pos/report/best-customers",
                    },
                    {
                        title: getFormattedMessage("customer.report.title"),
                        to: "/admin/pos/report/customers",
                        detail: "/admin/pos/report/customers/details",
                    },
                ],
            },
            {
                title: "currencies.title",
                name: "currencies",
                fontIcon: <FontAwesomeIcon icon={faDollarSign} />,
                to: "/admin/pos/currencies",
                class: "d-flex",
                permission: Permissions.MANAGE_CURRENCY,
                items: [
                    {
                        title: getFormattedMessage("currencies.title"),
                        to: "/admin/pos/currencies",
                    },
                ],
            },
            {
                title: "template.title",
                name: "template",
                fontIcon: <FontAwesomeIcon icon={faFile} />,
                to: "/admin/pos/email-templates",
                class: "d-flex",
                is_submenu: "true",
                permission: Permissions.MANAGE_EMAIL_TEMPLATES,
                subPath: {
                    emailTemplateSubPath: "/admin/pos/email-templates",
                    smsTemplateSubPath: "/admin/pos/sms-templates",
                    smsApiSubPath: "/admin/pos/sms-api",
                },
                subMenu: [
                    {
                        title: "email-template.title",
                        name: "email-templates",
                        fontIcon: <FontAwesomeIcon icon={faEnvelope} />,
                        to: "/admin/pos/email-templates",
                        class: "d-flex",
                        permission: Permissions.MANAGE_EMAIL_TEMPLATES,
                    },
                    {
                        title: "sms-template.title",
                        name: "sms-templates",
                        fontIcon: <FontAwesomeIcon icon={faSms} />,
                        to: "/admin/pos/sms-templates",
                        class: "d-flex",
                        permission: Permissions.MANAGE_SMS_TEMPLATES,
                    },
                    {
                        title: "sms-api.title",
                        name: "sms-api",
                        fontIcon: <FontAwesomeIcon icon={faCube} />,
                        to: "/admin/pos/sms-api",
                        class: "d-flex",
                        permission: Permissions.MANAGE_SMS_API,
                    },
                ],
            },
            {
                to: "/admin/pos/pos",
                class: "d-none",
                name: "pos",
                title: "header.pos.title",
                permission: Permissions.MANAGE_POS_SCREEN,
            },
            {
                title: "settings.title",
                name: "settings",
                fontIcon: <FontAwesomeIcon icon={faGear} />,
                to: "/admin/pos/lmpos-settings",
                prefixesPath: "/admin/pos/prefixes",
                mailSettingsPath: "/admin/pos/mail-settings",
                class: "d-flex",
                isSamePrefix: "true",
                permission: Permissions.MANAGE_SETTING,
                subTitles: [
                    { title: "prefix.title" },
                    { title: "mail-settings.title" },
                ],
                items: [
                    {
                        title: getFormattedMessage("settings.title"),
                        to: "/admin/pos/lmpos-settings",
                    },
                    {
                        title: getFormattedMessage("prefix.title"),
                        to: "/admin/pos/prefixes",
                    },
                    {
                        title: getFormattedMessage("mail-settings.title"),
                        to: "/admin/pos/mail-settings",
                    },
                ],
            },
        ],
    },
];
